stages:
  data_ingestion:
    cmd: python src/stages/data_ingestion.py
    deps:
      - data/raw/Fake.csv
      - data/raw/True.csv
      - src/stages/data_ingestion.py
    params:
      - data_ingestion.sample_size_per_class
      - data_ingestion.test_size
      - data_ingestion.random_state
    outs:
      - data/processed/train_data.joblib
      - data/processed/test_data.joblib

  feature_engineering:
    cmd: python src/stages/feature_engineering.py
    deps:
      - data/processed/train_data.joblib
      - data/processed/test_data.joblib
      - src/stages/feature_engineering.py
    params:
      - feature_engineering.max_features
      - feature_engineering.ngram_range
    outs:
      - data/processed/X_train_tfidf.joblib
      - data/processed/X_test_tfidf.joblib
      - data/processed/vectorizer.joblib

  model_building:
    cmd: python src/stages/model_building.py
    deps:
      - data/processed/X_train_tfidf.joblib
      - data/processed/X_test_tfidf.joblib
      - src/stages/model_building.py
    params:
      - model_building.model_name
      - model_building.solver
      - model_building.max_iter
      - model_building.n_estimators
      - model_building.max_depth
    metrics:
      - model/metrics.json:
          cache: false
    outs:
      - model/lr_fake_news_model.joblib