data_ingestion:
  sample_size_per_class: 10000
  test_size: 0.2
  random_state: 42

feature_engineering:
  max_features: 15000
  ngram_range: [1, 3]

model_building:
  model_name: "logistic_regression"
  solver: "liblinear"
  max_iter: 1000
  n_estimators: 100  # For future ensemble models
  max_depth: 10      # For future tree-based models