name: Test AWS Secrets

on:
  push:
    branches: [ main, master ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Test AWS connectivity
      run: |
        echo "Testing AWS credentials..."
        aws sts get-caller-identity
        echo "✅ AWS credentials work!"
        
        echo "Testing S3 access..."
        aws s3 ls ${{ secrets.DVC_S3_BUCKET }}
        echo "✅ S3 access works!"
